// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package weaviate

import (
	"weaviate-gui/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// GetConnection provides a mock function for the type MockStorage
func (_mock *MockStorage) GetConnection(id int64, decrypt bool) (*models.Connection, error) {
	ret := _mock.Called(id, decrypt)

	if len(ret) == 0 {
		panic("no return value specified for GetConnection")
	}

	var r0 *models.Connection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, bool) (*models.Connection, error)); ok {
		return returnFunc(id, decrypt)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, bool) *models.Connection); ok {
		r0 = returnFunc(id, decrypt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Connection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64, bool) error); ok {
		r1 = returnFunc(id, decrypt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnection'
type MockStorage_GetConnection_Call struct {
	*mock.Call
}

// GetConnection is a helper method to define mock.On call
//   - id
//   - decrypt
func (_e *MockStorage_Expecter) GetConnection(id interface{}, decrypt interface{}) *MockStorage_GetConnection_Call {
	return &MockStorage_GetConnection_Call{Call: _e.mock.On("GetConnection", id, decrypt)}
}

func (_c *MockStorage_GetConnection_Call) Run(run func(id int64, decrypt bool)) *MockStorage_GetConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(bool))
	})
	return _c
}

func (_c *MockStorage_GetConnection_Call) Return(connection *models.Connection, err error) *MockStorage_GetConnection_Call {
	_c.Call.Return(connection, err)
	return _c
}

func (_c *MockStorage_GetConnection_Call) RunAndReturn(run func(id int64, decrypt bool) (*models.Connection, error)) *MockStorage_GetConnection_Call {
	_c.Call.Return(run)
	return _c
}
