// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['updater']['Updater']['CheckForUpdates']();
}

export function Execute() {
  return window['go']['updater']['Updater']['Execute']();
}

export function GetVersion() {
  return window['go']['updater']['Updater']['GetVersion']();
}

export function ReleaseByTagURL() {
  return window['go']['updater']['Updater']['ReleaseByTagURL']();
}

export function Restart() {
  return window['go']['updater']['Updater']['Restart']();
}

export function SetRuntimeContext(arg1) {
  return window['go']['updater']['Updater']['SetRuntimeContext'](arg1);
}
