// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {context} from '../models';

export function CheckForUpdates():Promise<updater.w_CheckForUpdatesResponse>;

export function Execute():Promise<void>;

export function GetVersion():Promise<string>;

export function ReleaseByTagURL():Promise<string>;

export function Restart():Promise<void>;

export function SetRuntimeContext(arg1:context.w_Context):Promise<void>;
