// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sql

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEncrypter creates a new instance of MockEncrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncrypter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncrypter {
	mock := &MockEncrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEncrypter is an autogenerated mock type for the Encrypter type
type MockEncrypter struct {
	mock.Mock
}

type MockEncrypter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncrypter) EXPECT() *MockEncrypter_Expecter {
	return &MockEncrypter_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockEncrypter
func (_mock *MockEncrypter) Decrypt(data string) (string, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncrypter_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockEncrypter_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - data
func (_e *MockEncrypter_Expecter) Decrypt(data interface{}) *MockEncrypter_Decrypt_Call {
	return &MockEncrypter_Decrypt_Call{Call: _e.mock.On("Decrypt", data)}
}

func (_c *MockEncrypter_Decrypt_Call) Run(run func(data string)) *MockEncrypter_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEncrypter_Decrypt_Call) Return(s string, err error) *MockEncrypter_Decrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEncrypter_Decrypt_Call) RunAndReturn(run func(data string) (string, error)) *MockEncrypter_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptSecret provides a mock function for the type MockEncrypter
func (_mock *MockEncrypter) DecryptSecret(data string) (string, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for DecryptSecret")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncrypter_DecryptSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptSecret'
type MockEncrypter_DecryptSecret_Call struct {
	*mock.Call
}

// DecryptSecret is a helper method to define mock.On call
//   - data
func (_e *MockEncrypter_Expecter) DecryptSecret(data interface{}) *MockEncrypter_DecryptSecret_Call {
	return &MockEncrypter_DecryptSecret_Call{Call: _e.mock.On("DecryptSecret", data)}
}

func (_c *MockEncrypter_DecryptSecret_Call) Run(run func(data string)) *MockEncrypter_DecryptSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEncrypter_DecryptSecret_Call) Return(s string, err error) *MockEncrypter_DecryptSecret_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEncrypter_DecryptSecret_Call) RunAndReturn(run func(data string) (string, error)) *MockEncrypter_DecryptSecret_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockEncrypter
func (_mock *MockEncrypter) Encrypt(data string) (string, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncrypter_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockEncrypter_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - data
func (_e *MockEncrypter_Expecter) Encrypt(data interface{}) *MockEncrypter_Encrypt_Call {
	return &MockEncrypter_Encrypt_Call{Call: _e.mock.On("Encrypt", data)}
}

func (_c *MockEncrypter_Encrypt_Call) Run(run func(data string)) *MockEncrypter_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEncrypter_Encrypt_Call) Return(s string, err error) *MockEncrypter_Encrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEncrypter_Encrypt_Call) RunAndReturn(run func(data string) (string, error)) *MockEncrypter_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
