// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {weaviate} from '../models';

export function Connect(arg1:number):Promise<void>;

export function Disconnect(arg1:number):Promise<void>;

export function GetCollectionNames(arg1:number):Promise<Array<string>>;

export function TestConnection(arg1:weaviate.TestConnectionInput):Promise<void>;
