// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {weaviate} from '../models';

export function Connect(arg1:number):Promise<void>;

export function Disconnect(arg1:number):Promise<void>;

export function GetCollections(arg1:number):Promise<Array<models.Class>>;

export function GetObjectsPaginated(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<weaviate.PaginatedObjectResponse>;

export function GetTenants(arg1:number,arg2:string):Promise<Array<models.Tenant>>;

export function GetTotalObjects(arg1:number,arg2:string,arg3:string):Promise<number>;

export function TestConnection(arg1:weaviate.TestConnectionInput):Promise<void>;
