// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupModulesEnabled(arg1) {
  return window['go']['weaviate']['Weaviate']['BackupModulesEnabled'](arg1);
}

export function CancelBackup(arg1, arg2, arg3) {
  return window['go']['weaviate']['Weaviate']['CancelBackup'](arg1, arg2, arg3);
}

export function ClusterStatus(arg1) {
  return window['go']['weaviate']['Weaviate']['ClusterStatus'](arg1);
}

export function Connect(arg1) {
  return window['go']['weaviate']['Weaviate']['Connect'](arg1);
}

export function CreateBackup(arg1, arg2) {
  return window['go']['weaviate']['Weaviate']['CreateBackup'](arg1, arg2);
}

export function DeleteCollection(arg1, arg2) {
  return window['go']['weaviate']['Weaviate']['DeleteCollection'](arg1, arg2);
}

export function DeleteObject(arg1, arg2, arg3, arg4) {
  return window['go']['weaviate']['Weaviate']['DeleteObject'](arg1, arg2, arg3, arg4);
}

export function Disconnect(arg1) {
  return window['go']['weaviate']['Weaviate']['Disconnect'](arg1);
}

export function GetCollections(arg1) {
  return window['go']['weaviate']['Weaviate']['GetCollections'](arg1);
}

export function GetCreationStatus(arg1, arg2) {
  return window['go']['weaviate']['Weaviate']['GetCreationStatus'](arg1, arg2);
}

export function GetObjectsPaginated(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['weaviate']['Weaviate']['GetObjectsPaginated'](arg1, arg2, arg3, arg4, arg5);
}

export function GetRestoreStatus(arg1, arg2, arg3) {
  return window['go']['weaviate']['Weaviate']['GetRestoreStatus'](arg1, arg2, arg3);
}

export function GetTenants(arg1, arg2) {
  return window['go']['weaviate']['Weaviate']['GetTenants'](arg1, arg2);
}

export function GetTotalObjects(arg1, arg2, arg3) {
  return window['go']['weaviate']['Weaviate']['GetTotalObjects'](arg1, arg2, arg3);
}

export function ListBackups(arg1, arg2) {
  return window['go']['weaviate']['Weaviate']['ListBackups'](arg1, arg2);
}

export function NodesStatus(arg1) {
  return window['go']['weaviate']['Weaviate']['NodesStatus'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['weaviate']['Weaviate']['RestoreBackup'](arg1, arg2);
}

export function Search(arg1, arg2, arg3, arg4) {
  return window['go']['weaviate']['Weaviate']['Search'](arg1, arg2, arg3, arg4);
}

export function TestConnection(arg1) {
  return window['go']['weaviate']['Weaviate']['TestConnection'](arg1);
}

export function UsersEnabled(arg1) {
  return window['go']['weaviate']['Weaviate']['UsersEnabled'](arg1);
}
