// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['weaviate']['Weaviate']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['weaviate']['Weaviate']['Disconnect'](arg1);
}

export function GetCollectionNames(arg1) {
  return window['go']['weaviate']['Weaviate']['GetCollectionNames'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['weaviate']['Weaviate']['TestConnection'](arg1);
}
