name: 'Compress'
description: 'Compress built files'

inputs:
  file-name:
    description: 'zip file name'
    required: true

runs:
  using: composite
  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@v4.0.0
      with:
        cosign-release: 'v3.0.3'

    - if: runner.os == 'Linux'
      shell: bash
      working-directory: build/bin
      run: |
        zip -r ${{ inputs.file-name }}.linux.zip *
        # Sign using keyless mode
        cosign sign-blob --yes --bundle ${{ inputs.file-name }}.linux.sig ${{ inputs.file-name }}.linux.zip --new-bundle-format=true

    - if: runner.os == 'Windows'
      shell: pwsh
      working-directory: build/bin
      run: |
        Compress-Archive -Path * -Destination "${{ inputs.file-name }}.windows.zip"
        # Sign using keyless mode
        cosign sign-blob --yes --bundle ${{ inputs.file-name }}.windows.sig ${{ inputs.file-name }}.windows.zip --new-bundle-format=true

    - if: runner.os == 'macOs'
      shell: bash
      working-directory: build/bin
      run: |
        zip -r ${{ inputs.file-name }}.macos.zip *
        # Sign using keyless mode
        cosign sign-blob --yes --bundle ${{ inputs.file-name }}.macos.sig ${{ inputs.file-name }}.macos.zip --new-bundle-format=true
