// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package updater

import (
	"github.com/Masterminds/semver"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAssetVerifier creates a new instance of MockAssetVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssetVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssetVerifier {
	mock := &MockAssetVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAssetVerifier is an autogenerated mock type for the AssetVerifier type
type MockAssetVerifier struct {
	mock.Mock
}

type MockAssetVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssetVerifier) EXPECT() *MockAssetVerifier_Expecter {
	return &MockAssetVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockAssetVerifier
func (_mock *MockAssetVerifier) Verify(assetFilename string, sigFilename string, version string) error {
	ret := _mock.Called(assetFilename, sigFilename, version)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(assetFilename, sigFilename, version)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAssetVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAssetVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - assetFilename
//   - sigFilename
//   - version
func (_e *MockAssetVerifier_Expecter) Verify(assetFilename interface{}, sigFilename interface{}, version interface{}) *MockAssetVerifier_Verify_Call {
	return &MockAssetVerifier_Verify_Call{Call: _e.mock.On("Verify", assetFilename, sigFilename, version)}
}

func (_c *MockAssetVerifier_Verify_Call) Run(run func(assetFilename string, sigFilename string, version string)) *MockAssetVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAssetVerifier_Verify_Call) Return(err error) *MockAssetVerifier_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAssetVerifier_Verify_Call) RunAndReturn(run func(assetFilename string, sigFilename string, version string) error) *MockAssetVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// Download provides a mock function for the type MockSource
func (_mock *MockSource) Download(progressCallback func(float64)) (string, error) {
	ret := _mock.Called(progressCallback)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(func(float64)) (string, error)); ok {
		return returnFunc(progressCallback)
	}
	if returnFunc, ok := ret.Get(0).(func(func(float64)) string); ok {
		r0 = returnFunc(progressCallback)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(func(float64)) error); ok {
		r1 = returnFunc(progressCallback)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSource_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockSource_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - progressCallback
func (_e *MockSource_Expecter) Download(progressCallback interface{}) *MockSource_Download_Call {
	return &MockSource_Download_Call{Call: _e.mock.On("Download", progressCallback)}
}

func (_c *MockSource_Download_Call) Run(run func(progressCallback func(float64))) *MockSource_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(float64)))
	})
	return _c
}

func (_c *MockSource_Download_Call) Return(s string, err error) *MockSource_Download_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSource_Download_Call) RunAndReturn(run func(progressCallback func(float64)) (string, error)) *MockSource_Download_Call {
	_c.Call.Return(run)
	return _c
}

// NewVersionExists provides a mock function for the type MockSource
func (_mock *MockSource) NewVersionExists(version *semver.Version) (*NewVersionExistsResponse, error) {
	ret := _mock.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for NewVersionExists")
	}

	var r0 *NewVersionExistsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*semver.Version) (*NewVersionExistsResponse, error)); ok {
		return returnFunc(version)
	}
	if returnFunc, ok := ret.Get(0).(func(*semver.Version) *NewVersionExistsResponse); ok {
		r0 = returnFunc(version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NewVersionExistsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*semver.Version) error); ok {
		r1 = returnFunc(version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSource_NewVersionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewVersionExists'
type MockSource_NewVersionExists_Call struct {
	*mock.Call
}

// NewVersionExists is a helper method to define mock.On call
//   - version
func (_e *MockSource_Expecter) NewVersionExists(version interface{}) *MockSource_NewVersionExists_Call {
	return &MockSource_NewVersionExists_Call{Call: _e.mock.On("NewVersionExists", version)}
}

func (_c *MockSource_NewVersionExists_Call) Run(run func(version *semver.Version)) *MockSource_NewVersionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*semver.Version))
	})
	return _c
}

func (_c *MockSource_NewVersionExists_Call) Return(newVersionExistsResponse *NewVersionExistsResponse, err error) *MockSource_NewVersionExists_Call {
	_c.Call.Return(newVersionExistsResponse, err)
	return _c
}

func (_c *MockSource_NewVersionExists_Call) RunAndReturn(run func(version *semver.Version) (*NewVersionExistsResponse, error)) *MockSource_NewVersionExists_Call {
	_c.Call.Return(run)
	return _c
}
