// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sql} from '../models';

export function GetConnections():Promise<Array<sql.Connection>>;

export function RemoveConnection(arg1:number):Promise<void>;

export function SaveConnection(arg1:sql.Connection):Promise<number>;

export function UpdateFavorite(arg1:number,arg2:boolean):Promise<void>;
