// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetConnection(arg1:number):Promise<models.w_Connection>;

export function GetConnections():Promise<Array<models.w_Connection>>;

export function RemoveConnection(arg1:number):Promise<void>;

export function SaveConnection(arg1:models.w_Connection):Promise<number>;

export function UpdateFavorite(arg1:number,arg2:boolean):Promise<void>;
