// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnection(arg1) {
  return window['go']['sql']['Storage']['GetConnection'](arg1);
}

export function GetConnections() {
  return window['go']['sql']['Storage']['GetConnections']();
}

export function RemoveConnection(arg1) {
  return window['go']['sql']['Storage']['RemoveConnection'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['sql']['Storage']['SaveConnection'](arg1);
}

export function UpdateFavorite(arg1, arg2) {
  return window['go']['sql']['Storage']['UpdateFavorite'](arg1, arg2);
}
